# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loco
  labels:
    app: loco
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loco
  template:
    metadata:
      labels:
        app: loco
    spec:
      containers:
      - name: loco
        image: sarkararnab/loco:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
