# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loco
spec:
  type: NodePort
  selector:
    app: loco
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # NodePort explicitly set for access, or omit for random